Once upon a time, in a forest there lived a monkey who resided on a berry tree which was on the banks of a river.
In the same forest,there lived a crocodile and his wife.The crocodile and the monkey were thick friends as the monkey helped the 
crocodile by plucking and giving him berries.One day,the crocodile's wife asked the crocodile to get the monkey's brain for it to eat...
